spring.application.name=cms
server.port=8086

### Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=cms
spring.kafka.client-id=cms
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.auto-offset-reset=earliest

### Kafka topics
com.bttls.cms.topics.sensor.temperature=sensor.temperature
com.bttls.cms.topics.sensor.humidity=sensor.humidity
com.bttls.cms.topics.alarm.threshold=alarm.threshold
