spring.application.name=cms
server.port=8086

### Kafka configuration
spring.kafka.consumer.group-id=cms
spring.kafka.client-id=cms

### Kafka topics
com.bttls.kafka.topics.sensor.temperature=sensor.temperature
com.bttls.kafka.topics.sensor.humidity=sensor.humidity
com.bttls.kafka.topics.alarm.threshold=alarm.threshold
