spring.application.name=whs1
server.port=8087

com.bttls.whs1.udp.sensor.temperature.port=3344
com.bttls.whs1.udp.sensor.humidity.port=3355

### Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=whs1

### Kafka topics
com.bttls.whs1.topics.sensor.temperature=sensor.temperature
com.bttls.whs1.topics.sensor.humidity=sensor.humidity
com.bttls.whs1.topics.alarm.threshold=alarm.threshold
