spring.application.name=whs1
server.port=8087

com.bttls.whs1.udp.sensor.temperature.port=3344
com.bttls.whs1.udp.sensor.humidity.port=3355

### Kafka configuration
spring.kafka.consumer.group-id=whs1

### Kafka topics
com.bttls.whs1.kafka.sensor.monitor.temperature.topic=sensor.monitor.temperature
com.bttls.whs1.kafka.sensor.monitor.humidity.topic=sensor.monitor.humidity
com.bttls.whs1.kafka.sensor.alarm.threshold.topic = whs1.sensor.alarm.threshold
